### ISSUE TITLE
Node stuck

### ISSUE THREAD

**Issue by szhelonkin** [neutroncoin/neutron#37] opened 2020-02-06 13:37 UTC
Node stop answering to rpc requests.
Debug log [https://yadi.sk/d/KRCBlIXu3SA7kQ](url)

**Comment by adam-waldenberg** [comment] 2020-02-06 13:58
Thank you.

This indeed looks very strange. Before you start neutrond could you please execute `ulimit -c unlimited`? This will  create a core dump in the current working directory if one of the threads happen to crash.

When this happens could you also provide the outputs of, `ps -eT | grep eutron` and `free -m` on that particular server. This will allow us to see the amount of free memory and all the running threads related to neutron.

**Comment by adam-waldenberg** [comment] 2020-02-07 01:42
@szhelonkin I noticed you are using Boost 1.58 ... While we support it, this version is from 2015 by now. It's hard to tell for sure - but this *might* be the cause of your issues. If you update the version and it solves your problems we might want to look into dropping suport for it or outputting a warning during compilation.

**Comment by adam-waldenberg** [comment] 2020-03-17 03:24
Closing this as I have not heard anything for over a month concerning this issue.

**Closed as completed by adam-waldenberg** 2020-03-17 03:24 UTC
