### ISSUE TITLE
Neutron-qt_v1.1.2_win32.exe version is wrong..

### ISSUE THREAD

**Issue by yhyim** [neutroncoin/neutron#4] opened 2017-09-28 06:47 UTC
I download Neutron-qt_v1.1.2_win32.exe file and run it.
then check the version it shows "version" : "v1.1.1.0-unk",
v1.1.1.0-unk

Where can I find 1.1.2 version for window?

**Comment by eroninjapan** [comment] 2017-09-28 08:07
That is the correct v1.1.2 file. The version number is just reported incorrectly. It should be fixed in the next version.

Closing as this is a duplicate of #3

**Closed as completed by eroninjapan** 2017-09-28 08:07 UTC
